---
- name: Import common playbook
  import_playbook: common.yml

- hosts: localhost
  roles:
    - role: homebrew
    - role: terminal
    - role: docker
    - role: kubernetes
    - role: java
    - role: scala
    - role: apache_spark
    - role: git
    - role: python
    - role: go
    - role: rust
    - role: kotlin
    - role: zed
    - role: firefox
    - role: vlc
    - role: calibre
    - role: proton_privacy
    - role: discord
    - role: signal
    - role: caprine
    - role: obsidian
    - role: postman
    - role: spotify
    - role: qobuz
    - role: utils
    - role: llm
    - role: qemu
    - role: raspberrypi
    - role: gpg
    - role: neovim
    - role: tmux
    - role: jetbrains
