---
- name: Import common playbook
  import_playbook: common.yml

- hosts: localhost
  roles:
    - role: homebrew
    - role: terminal
    - role: utils
    - role: gpg
    - role: neovim
    - role: tmux
    - role: search

