---
- name: Import common playbook
  import_playbook: common.yml

- hosts: localhost
  roles:
    - base
    - aur_helper
    - env_setup
    - maintenance
    - utils
    - git
    - python
    - scala
    - apache_spark
    - go
    - rust
    - kotlin
    - zed
    - firefox
    - vlc
    - calibre
    - proton_privacy
    - discord
    - signal
    - caprine
    - obsidian
    - vscodium
    - browsers
    - chats
    - spotify
    - qobuz
    - crypto
    - 1password
    - vpn
    - yubikey
    - devices
    - security
    - pw_cracking
    - aws_cli_v2
    - docker
    - java
    - jetbrains
    - postman
    - kubernetes
    - llm
    - qemu
    - raspberrypi
    - virtualbox
    - documents
    - search
    - gpg
    - neovim
    - tmux
...
